### ISSUE TITLE
Bad response after calling "drv_VEL=1,?" command

### ISSUE THREAD

**Issue by RexJoker** [vAtomowy/Mobile-robot-drive-based-on-stepper-28byj-48-motor#1]
Hi Artur!
When i tried to test my firmware at Robot Operating System, i found a bug in functionality of your PICO Drivers:
   After calling command: "drv_VEL=1,?" through UART interface, unfortunately, the device is not responding as it should be. This is what i am sending:
![TX_commands](https://user-images.githubusercontent.com/29863685/202519636-d0c33baa-0169-4c57-8181-4c98bbfc2f2b.png)
And this is what i got from your drivers:
![RX_commands](https://user-images.githubusercontent.com/29863685/202519734-358c72cc-64e6-4386-9eca-0637cd11ef99.png)
I am assuming that this is some sort of software defect. My "Move control" firmware, described for ROS, after calling such a command is expecting some numerical integer value within the range <-255,255>

**Comment by vAtomowy** [comment]
Bug fix ! good night
